version: '3'

services:
  haproxy:
    image: cangrowha
    networks:
      cangrownet:
        ipv4_address: 172.30.0.2
    container_name: haproxy
    ports:
      - "80:80"

  redis:
    image: redis
    networks:
      cangrownet:
        ipv4_address: 172.30.0.3
    container_name: redis
    depends_on:
      - haproxy

  node1:
    image: weather_app
    environment:
      - REDIS_HOST=172.30.0.3
      - REDIS_PORT=6379
    networks:
      cangrownet:
        ipv4_address: 172.30.0.4
    container_name: node1
    depends_on:
      - redis

  node2:
    image: weather_app
    environment:
      - REDIS_HOST=172.30.0.3
      - REDIS_PORT=6379
    networks:
      cangrownet:
        ipv4_address: 172.30.0.5
    container_name: node2
    depends_on:
      - node1

  node3:
    image: weather_app
    environment:
      - REDIS_HOST=172.30.0.3
      - REDIS_PORT=6379
    networks:
      cangrownet:
        ipv4_address: 172.30.0.6
    container_name: node3
    depends_on:
      - node2

networks:
  cangrownet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
